cls/urls.py
from django.urls import path 
from . import views

app_name = "cls"

urlpatterns = [
    path('',views.home,name='home')
]

venues/urls.py
from django.urls import path
from . import views

app_name = 'venues'



urlpatterns=[
    path('venue', views.venue_home, name= 'venue'),
    path('detail/<str:slug>', views.details, name='detail'),
    path('createvenue', views.createvenue, name='createvenue'),
    path('venue_edit/<str:id>', views.venue_edit, name='venue_edit'),
    path('remove_venue', views.remove_venue, name='remove_venue'),

]

wos/urls.py
from django.contrib import admin
from django.urls import path, include
# from base.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home, name='home'),

    path('shows/', include('shows.urls')),
    # path('auditions/', include('auditions.urls')),
    # path('classes/', include('classes.urls')),
    # path('playreads/', include('playreads.urls')),
    # path('venues/', include('venues.urls')),
]

venues/models.py
from datetime import datetime, date

from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.

#general city names.. like chicago, as many venues could be in chicago... for filtering purposes
class GeneralLocation(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name
    

#VENUE_CHOICES = (
#    ('R', 'Renting'),
#    ('H', 'Hiring'),
#)

VENUE_STATUS = (
    ('', '............'),
    ('F', 'Free'),
    ('P', 'Paid'),
)


class Venues(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    general = models.ForeignKey(GeneralLocation, on_delete =models.CASCADE)
    name = models.TextField(max_length=250)
    slug = models.SlugField()
#    image = models.ImageField(upload_to = 'venues', null=True, blank=True)
#    choices = models.CharField(choices=VENUE_CHOICES, max_length=30, null=True, blank=True)
    location = models.TextField(max_length=250, null=True, blank=True)
    capacity = models.CharField(max_length=50, null=True, blank=True)
    description = RichTextField(blank=True, null=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    fee = models.IntegerField()
    status = models.CharField(max_length=5, choices=VENUE_STATUS, default= "Free")

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-fee']

    def __str__(self):
        return f"{self.name} located at {self.location}"



# users to request for renting from the detail page
class RequestRent(models.Model):
    venue  = models.ForeignKey(Venues, on_delete =models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    start_date = models.DateField()
    end_date = models.DateField()

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} requested for {self.venue}"

        

venues/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Venues, GeneralLocation, RequestRent



class FilteringForm(forms.ModelForm):
    status_list = [('', '----------'), ('F', 'Free'),('P', 'Paid'),]
    start_date = forms.DateField(label='start_date', widget=forms.DateInput(
                       attrs={'PlaceHolder':'yyy-mm-dd'}), required= False              
    )
    end_date = forms.DateField(label='end_date', widget=forms.DateInput(
                       attrs={'PlaceHolder':'yyy-mm-dd'}), required= False              
    )   
    
    status = forms.CharField(label='status', widget=forms.Select(
                       choices= status_list ), required= False
    )
    class Meta:
        model = Venues
        fields = ['start_date','end_date','status',]


class CreatVenueForm(forms.ModelForm):
    class Meta:
        '''
            metadata
        '''
        model = Venues
        fields = '__all__'





class RequestRentForm(forms.ModelForm):
    name = forms.CharField(label = 'Name', widget=forms.TextInput(
                attrs={'PlaceHolder': "John Doe"}
            )
    )
    email=forms.EmailField(label = 'Email', widget= forms.EmailInput(
                attrs:={'PlaceHolder': "Work email"}
            )
    )
    start_date= forms.DateField(label= 'Start', widget=forms.DateInput(
            attrs:={'PlaceHolder': "yyy-mm-dd"}
            )
    )
    end_date= forms.DateField(label= 'End', widget=forms.DateInput(
            attrs:={'PlaceHolder': "yyy-mm-dd"}
            )
    )

    class Meta:
        model = RequestRent
        fields = ['name','email','start_date','end_date',]

    
    

venues/views.py
from dataclasses import dataclass
from datetime import datetime, date


from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


from .models import Venues, GeneralLocation, RequestRent
from .forms import FilteringForm,CreatVenueForm, RequestRentForm
# Create your views here.


@dataclass
class G:
	ven = Venues.objects
	


def venue_home(request):

    ############ for paginating ############
    pag= Paginator(G.ven.all(),3)
    page_number= request.GET.get('page',all)
    ven=pag.get_page(page_number)
    ############ paginating end ############

    venue_count = G.ven.all().count()
    form = FilteringForm(request.POST or None)
    
    if request.method == 'POST':
                 
        try:
            try:
                #filtering from venues
                ven = G.ven.filter(
                    start_date__range= [ form['start_date'].value(),
                                        form['end_date'].value()
                                        ],
                    status__icontains= form['status'].value(),
                )
            except:
                ven = G.ven.filter(
                    status__icontains= form['status'].value(),
                )
            else:
                ven = ven
        except:
            #searching
            search = request.POST['itemsearch']
            ven=G.ven.filter(
                Q(general__name__icontains=search) |
                Q(name__icontains=search) |
                Q(location__icontains=search)
            ).distinct()
        else:
            ven = ven

    return render(request, 'venues/venue.html', {'ven': ven,'venue_count':venue_count,'form':form,})



def details(request, slug):
    detail = G.ven.get(slug=slug)

    rent = RequestRentForm(instance= detail)
    if request.method == 'POST':
        rent = RequestRentForm(request.POST, instance=detail)
        if rent.is_valid(): 
            rent.save(commit=False)
            #transfering the filled form to the db model
            c= RequestRent(venue =G.ven.get(slug=slug), 
                    name=rent.cleaned_data['name'], 
                    email=rent.cleaned_data['email'], start_date=rent.cleaned_data['start_date'], 
                    end_date=rent.cleaned_data['end_date'],
                    created=datetime.now() 
            )
            c.save()
            return redirect('detail', detail.slug )
    else:
        rent= RequestRentForm()

    return render(request, 'venues/detail.html', {'detail': detail, 'rent': rent,})


@login_required(login_url='login')
def createvenue(request):
    form = CreatVenueForm()
    if request.method == 'POST':
        form = CreatVenueForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('venue')
    
    return render(request, 'venues/venue_post.html', {'form': form})


@login_required(login_url='login')
def venue_edit(request, id):
    edit = G.ven.get(pk=id)
    form = CreatVenueForm(instance=edit)
    if request.method == 'POST':
        form = CreatVenueForm(request.POST, instance=edit)
        if form.is_valid():
            form.save()
            return redirect('venue', edit.pk)
        else:
            form = CreatVenueForm(instance= edit)
    
    return render(request, 'venues/venue_post.html', {'form': form})

def remove_venue(request):
    deletevenue = request.POST['deletevenue']
    Venues.objects.filter(pk=deletevenue).delete()
    return redirect('venue')

venues/templates/venues/detail.html
{% extends 'main_venue.html' %}

{% block content%}

<h1> {{detail.name}} </h1>
<a href="{% url 'venues:venue_edit' detail.pk %}"> Edit </a>
<p> {{detail.description| safe}} </p>
<span>Available from: {{detail.start_date|date:"D, M d, Y"}} </span> </br>
<span>Capacity: {{detail.capacity}} </span>

<!-- ######################## form for venue request ################################ -->
<div>
    <p> Fill the form to request for this venue </p>
    <form action="{% url 'venues:detail' detail.slug %}" method="POST">
        {% csrf_token%}
        {{rent.as_p}}
        <input type="submit" value="Request">
    </form>
</div>


{% endblock %}

venues/templates/venues/venue.html
{% extends "main_venue.html" %} {% block content%}
<style>
    .home-container {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(20rem, 0.05fr));
    }
</style>

<div class="home-container">
    <div>
        <h3>Browse Genre</h3>
        <hr />
        <div>
            <a href="{% url 'venues:venue' %}">All</a>
        </div>

        <!-- ######################## venue filtering ################################ -->
        <div>
            <form action="{% url 'venues:venue' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" style=" background: transparent; border: none; text-decoration: underline; ">filter</button>
            </form>
        </div>
    </div>

    <!-- ######################## display venues ################################ -->
    <div>
        <h5>{{venue_count}} available venues</h5>
        <a href="{% url 'venues:createvenue' %}">Post Venue</a>
        <br>
        <div>
            {% for v in ven %}
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(10rem, 0.05fr));">
                <div>
                    <a href="{% url 'venues:detail' v.slug %}">
                        <span style="position: absolute;"> Venue {{v.get_status_display}} </span>
                        <img src="{{v.image.url}}" alt="" height="100" width="100">
                    </a>
                </div>
                <div>
                    <h4>
                        <a href="{% url 'venues:detail' v.slug %}"> {{v.name}} </a> &nbsp;
                    </h4>
                    <h6>
                        <a href="{% url 'venues:detail' v.slug %}"> {{v.location}} </a> &nbsp;
                    </h6>

                    <span>Available from: {{v.start_date|date:"D, M d, Y"}} </span>
                    <br>
                    <small>Fee: {{v.fee}}$ </small>
                    <!-- ######################## delete a specific venue ################################ -->
                    {% if request.user == v.host.user %}
                    <form action="{% url 'venues:remove_venue' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="deletevenue" value="{{item.id}}">
                        <button type="submit">Delete</button>
                    </form>
                    {% endif %}
                    <hr>
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- ######################## venue pagination ################################ -->
        <nav aria-label="Page navigation example">
            <ul class="pagination pt-5 mt-5 justify-content-center">

                {% if ven.has_previous %}
                    <a class="page-link mi" href="?page={{ven.previous.page_number}}">Previous</a>
                {% endif %}

                {% for item in ven.paginator.page_range %}
                    {% if ven.number == item %}
                       <a class="page-link im" href="?page={{item}}">{{item}}</a>
                    {% else %}
                        <a class="page-link im" href="?page={{item}}">{{item}}</a>
                    {% endif %}
                {% endfor %}

                {% if ven.has_next %}
                    <a class="page-link mi" href="?page={{ven.next.page_number}}">Next</a>
                {% endif %}
            </ul>

        </nav>
    </div>


</div>


{% endblock %}

venues/templates/venues/venue_post.html
{% extends 'main_venue.html' %}

{% block content %}
<div>
    <form method="POST" action="">
        {% csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
</div>

{% endblock %}