classes/urls.py
from django.urls import path 
from . import views

app_name = "classes"

urlpatterns = [
    path('',views.home,name='home'), 
    path('detail/<int:pk>',views.detail, name='detail')
]

cls/urls.py
from django.urls import path 
from . import views

app_name = "cls"

urlpatterns = [
    path('',views.home,name='home')
]

wos/urls.py
from django.contrib import admin
from django.urls import path, include
# from base.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home, name='home'),

    path('shows/', include('shows.urls')),
    # path('auditions/', include('auditions.urls')),
    # path('classes/', include('classes.urls')),
    # path('playreads/', include('playreads.urls')),
    # path('venues/', include('venues.urls')),
]

base/models.py
from django.db import models

# Create your models here.

classes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import datetime
from django.conf import settings
import os

# Create your models here.

class ClassUser(models.Model): 
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_instructor = models.BooleanField(default=False)

    def __str__(self): 
        return f"{self.id}--{self.user.username}--{self.is_instructor}"

class Class(models.Model): 

    def upload_path(instance,filename): 
        now = datetime.now().date().strftime("%Y-%m-%d")
        filename = filename[:50]
        filename += f"-{now}"
        path = os.path.join(settings.CLASSES_UPLOADED_FOLDER,filename)
        return path

    name = models.CharField(max_length=100)
    owner = models.ForeignKey(ClassUser, on_delete=models.CASCADE, related_name="owner")
    instructor = models.ManyToManyField(ClassUser,null=True,blank=True)
    description = models.CharField(max_length=250)
    start_date = models.DateField()
    end_date = models.DateField(null=True,blank=True)
    start_time = models.TimeField()
    end_time = models.TimeField()
    schedule = models.CharField(max_length=100)
    image = models.FileField(upload_to=upload_path,null=True,blank=True)
    
    def __str__(self) :
        return f"{self.id}--{self.name}"
    
    class Meta:
        ordering = ['id']
        
    # Input Validation of this models are handled by pre_save and m2m_changed signals 

base/forms.py
# create your forms here

base/views.py
from django.shortcuts import render, redirect


# Create your views here.
def home(request):
    pass


    

classes/views.py
from django.shortcuts import render,get_object_or_404
from classes.models import Class,ClassUser
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.
def home(request):
    q=request.GET.get("q")
    if not q or q=="" or q=="None" :
        classes = Class.objects.all()
    else : 
        classes = Class.objects.filter(
            Q(name__icontains=q) |
            Q(owner__user__username__icontains=q) |
            Q(description__icontains=q) |
            Q(schedule__icontains=q) |
            Q(instructor__user__username__icontains=q)
         ).distinct()
    paginator = Paginator(classes,3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        'query':q,
        'classes':classes,
        'page_obj':page_obj
    }
    return render(request,'classes/home.html',context)

def detail(request,pk):
    class_detail = get_object_or_404(Class,pk=pk)
    context = {
        'class':class_detail
    }
    return render(request,'classes/detail.html',context)

classes/templates/classes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
    {% include 'classes/navbar.html' %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

classes/templates/classes/detail.html
{% extends 'classes/base.html' %}

{% block title%} {{class.name}} {% endblock title %}

{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="column">
            <img src="{{class.image.url}}" alt="">
            <h2>{{class.name}}</h2>
            <p>Owner : <span>{{class.owner.user.username}}</span></p>
            <p>Instructor(s):</p>
            <ul>
                {% for ins in class.instructor.all %}
                    <li><a href="">{{ins.user.username}}</a></li>
                {% endfor %}
            </ul>
            <p>Description:</p>
            <p>{{class.description}}</p>
            <p>Date:</p>
            <p><span>Start : {{class.start_date}}</span><span>, End : {{class.end_date}}</span></p>
            <p>Schedule:</p>
            <p><span>{{class.schedule}}</span><span>/{{class.start_time}}-{{class.end_time}}</span></p>
        </div>
        
    </div>
{% endblock content %}

classes/templates/classes/home.html
{% extends 'classes/base.html' %}

{% block title %}
    Class Home Page
{% endblock title %}


{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="row">
            <h1>WELCOME TO THE CLASSES</h1>
        </div>
    </div>
    <div class="container">
        <h3>Available Classes ({{classes.count}}) : </h3>
        <div class="row">
                {% for cls in page_obj %}
                <div class="col-4 d-flex align-items-stretch">
                    <div class="card d-flex" style="width:18rem">
                        <img src="{{cls.image.url}}" class="card-img-top" alt="LALA">
                        <div class="card-body d-flex flex-column">
                          <h5 class="card-title">{{cls.name}}</h5>
                          <p class="card-text">{{cls.description|truncatechars:100}}</p>
                          <div class="d-flex flex-row justify-content-start gap-3 flex-grow-1 flex-wrap">
                            <p class="h-1"> Instructor : </p>
                            {% for ins in cls.instructor.all %}
                                <a href="#" class="link-warning">{{ins.user.username}}</a>
                            {% endfor %}
                          </div>

                          <p class="card-text">
                            <a href="{% url 'classes:detail' cls.id %}" class="btn btn-primary">Detail</a>
                          </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination d-flex gap-2">
                <li class="page-item">
                    <a href="?page=1&q={{query}}">&laquo; first</a>
                </li>
                <li class="page-item">
                    {% if page_obj.has_previous %}

                    <a href="?page={{ page_obj.previous_page_number }}&q={{query}}">previous</a>
                    {% endif %}
                </li>
                <li class="page-item">
                    {{page_obj.number}} of {{page_obj.paginator.num_pages}}
                </li>
                <li class="page-item">
                    {% if page_obj.has_next %}
                    <a href="?page={{page_obj.next_page_number}}&q={{query}}">next</a>
                    {% endif %}
                </li>
                <li class="page-item">
                    <a href="?page={{ page_obj.paginator.num_pages }}&q={{query}}">last &raquo;</a>
                </li>
            </ul>
        </nav>
    </div>


{% endblock %}

classes/templates/classes/navbar.html
{% load static %}

<div class="container">
    <div class="row">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home' %}">Home</a>
              <button class="navbar-toggler" type="button"  data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Classes</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Instructors</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Other Cool Stuffs</a>
                  </li>
                </ul>
                <form action="{% url 'classes:home' %}" class="d-flex" role="search">
                  <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{request.user.username}}
                            </a>
                            <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Profile</a></li>
                            <li><a class="dropdown-item" href="#">My Classes</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Log out</a></li>
                            </ul>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
                        </li>
                    </ul>
                {% endif %}
              </div>
            </div>
          </nav>
    </div>
</div>